---
- name: 'Set timezone'
  include: timezone.yml

- name: 'Set hostname'
  include: hostname.yml

- name: 'Update ubuntu package cache'
  become: yes
  apt: update_cache=yes

- name: 'Upgrade to the lastest packages'
  become: yes
  apt: upgrade=dist

- name: 'LTS distribution upgrade'
  include: release.yml
