---
- name: 'Install prerequisites'
  become: yes
  apt: name={{item}} state=present
  with_items:
    - git
    - awscli
    - screen
    - sqlite3
    - supervisor

- name: 'nginx setup'
  include: nginx.yml

- name: 'python setup'
  include: python.yml

- name: 'flask setup'
  include: flask.yml
