---
- name: 'Install nginx'
  become: yes
  apt: package=nginx state=present

- name: 'Disable nginx default site'
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: 'Remove nginx default site config'
  become: yes
  file: path=/etc/nginx/sites-available/default state=absent

- name: 'Create nginx log directory'
  become: yes
  file: path=/var/log/nginx state=directory

- name: 'Modify nginx configuration (main)'
  become: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - Restart nginx

- name: 'Add site'
  become: yes
  template: src=templates/nginx-site.conf.j2 dest=/etc/nginx/sites-available/{{ domain }}

- name: 'Activate site'
  become: yes
  file: src=/etc/nginx/sites-available/{{ domain }} dest=/etc/nginx/sites-enabled/{{ domain }} state=link
