---
- name: 'Install base python packages'
  become: yes
  apt: name={{item}} state=present
  with_items:
    - python-dev
    - python-pip
    - python-virtualenv
    - libffi-dev
    - uwsgi-plugin-python

- name: 'Install supplemental python packages'
  action: pip name={{item}} virtualenv={{ webapps_dir }}/{{ app_name }}/venv state=present
  with_items:
    - bcrypt
    - flask_bcrypt
    - flask_login
    - flask_mail
    - flask_sqlalchemy
    - flask_wtf
    - paho-mqtt
    - sqlalchemy_migrate
    - flask_whooshalchemy
    - requests
    - pytz
    - boto3
    - pygal

