---
- name: Restart nginx
  become: yes
  service: name=nginx state=restarted

- name: Start nginx
  become: yes
  service: name=nginx state=started

- name: start supervisord
  become: yes
  service: name=supervisor state=started

- name: restart supervisord
  become: yes
  service: name=supervisor state=restarted
