---
- name: Restart nginx
  become: yes
  service: name=nginx state=restarted

- name: Start nginx
  become: yes
  service: name=nginx state=started

- name: restart uwsgi app
  become: yes
  supervisorctl: name={{ uwsgi_app_service_name }} state=restarted config=/etc/supervisor/supervisord.conf

- name: start supervisord
  become: yes
  service: name=supervisor state=started

- name: restart supervisord
  become: yes
  service: name=supervisor state=restarted
